import { useCaseMeta } from "@/lib/seo/use-cases/catalog";
import type { UseCaseCopy, UseCasePage, UseCaseSlug } from "@/lib/seo/use-cases/types";

const copy: Record<UseCaseSlug, UseCaseCopy> = {
  "thai-restaurant-menu": {
    title: "泰式餐厅菜单二维码设计",
    description:
      "免费设计泰式餐厅菜单二维码。链接 Google 表格、Drive PDF 或网页菜单——非点餐系统。自定义边框并下载可打印文件。",
    h1: "泰式餐厅菜单二维码设计",
    introduction:
      "设计可扫描的菜单二维码，让客人用手机查看泰语菜单。此码打开电子菜单（表格、PDF、网页）——不接收订单，不替代 Yumzi 或 ThaiQROrder 等 POS。",
    promise: "浏览器内免费生成，支持表格、Drive 和泰语边框文字。",
    body: [
      "多数泰式餐厅先从 Google 表格、Drive 上的 PDF 或网站菜单页开始。粘贴可在手机上快速打开的链接，选择菜单模板，覆膜桌卡前试扫。",
      "此二维码仅打开菜单供阅读——不是点餐、厨房单或结账系统。点餐请用 LINE 或现有 POS；此码只用于展示菜单。",
      "先在表格或链接页更新价格；仅当 URL 变更时才需重新下载 PNG。",
      "桌牌 QR 至少 30 mm（3 cm），四周留白 5 mm。就座距离 25–40 cm 应能舒适扫描。",
      "边框文字示例：ดูเมนู、สแกนดูเมนู、查看菜单。柜台可搭配 LINE 加好友码用于聊天下单。",
    ],
    examples: ["Google 表格查看链接", "Drive 或网站上的菜单 PDF", "泰/英双语或午餐套餐页"],
    howTo: [
      "发布可在手机上打开的菜单链接（表格、Drive PDF 或网页）",
      "粘贴网址，选择菜单模板，设置边框文字如 ดูเมนู",
      "下载至少 30 mm 的 PNG，并就座距离试扫",
      "试扫成功后再覆膜或打印桌牌",
    ],
    faqs: [
      { question: "这是点餐或 POS 系统吗？", answer: "不是。二维码仅打开电子菜单链接（表格、PDF、网页），不送厨，不替代 Yumzi 或 ThaiQROrder。" },
      { question: "必须有自己的网站吗？", answer: "不必。Google 表格、Drive PDF、Notion 均可。" },
      { question: "餐桌上建议多大尺寸？", answer: "QR 至少 30 mm，周围留白。A6 桌牌（105×148 mm）建议放在上部。" },
      { question: "应从多远能扫到？", answer: "覆膜或大批量印刷前，在就座高度 25–40 cm 处测试。" },
      { question: "如何在不全部重印的情况下更新价格？", answer: "编辑表格或链接页。若 URL 不变，已印二维码仍可用。" },
    ],
    helperHint: "粘贴泰语电子菜单链接，并保持边框文字简短。",
    frameText: "查看菜单",
    downloadFileName: "qr-menu-thai-restaurant.png",
    toolLinks: [
      { label: "网址二维码生成器", barePath: "/qr-code/url" },
      { label: "菜单模板库", barePath: "/templates/menu" },
      { label: "餐厅 LINE 联系二维码", barePath: "/use-cases/line-contact" },
    ],
  },
  "cafe-menu": {
    title: "免费咖啡店菜单二维码设计",
    description: "免费设计咖啡店菜单二维码，含打印尺寸与边框文字。链接饮品甜点，套用咖啡店模板并下载 PNG。",
    h1: "免费咖啡店菜单二维码设计",
    introduction: "设计咖啡店菜单二维码，让顾客在桌边或柜台打开饮品与甜点菜单。含咖啡店模板与边框文字如 咖啡店菜单。",
    promise: "免费、无需注册，提供咖啡店模板、打印尺寸建议与实时预览。",
    body: [
      "咖啡店常换季节饮品，单一菜单链接可在 URL 不变时更新内容而无需重印整本。",
      "链接到手机菜单页——不是点餐应用。桌上放菜单码，柜台可搭配 LINE 码。",
      "柜台贴纸宽 50 mm 或 A6 立牌（105×148 mm），QR 至少 25 mm，覆膜前先试扫。",
      "边框文字：咖啡店菜单、查看饮品。参见菜单与咖啡店模板库。",
    ],
    examples: ["饮品甜点网页菜单", "Google 表格或 PDF 饮品单", "早间优惠或会员菜单"],
    howTo: ["准备手机可快速打开的咖啡店菜单链接", "选择咖啡店或菜单模板，粘贴网址并设置边框", "下载至少 25 mm 的 PNG 并试扫", "试扫成功后再打印或覆膜"],
    faqs: [
      { question: "咖啡桌建议多大？", answer: "QR 至少 25–30 mm，贴纸或 A6 立牌，周围留白。" },
      { question: "可用于季节菜单吗？", answer: "可以。更新链接页；仅 URL 变更时重新下载。" },
      { question: "能通过此码下单吗？", answer: "不能，仅打开菜单。点餐请用 LINE 或 POS。" },
      { question: "顾客需要 App 吗？", answer: "不需要，手机相机即可。" },
    ],
    helperHint: "使用加载较快的咖啡店菜单链接，方便顾客快速点单。",
    frameText: "咖啡店菜单",
    downloadFileName: "qr-cafe-menu.png",
    toolLinks: [
      { label: "菜单模板库", barePath: "/templates/menu" },
      { label: "咖啡店模板库", barePath: "/templates/cafe" },
      { label: "咖啡店 WiFi 二维码", barePath: "/use-cases/free-wifi-no-signup" },
    ],
  },
  "free-wifi-no-signup": {
    title: "免费 WiFi 二维码（无需注册）",
    description: "免费创建咖啡店/店铺 WiFi 二维码。密码仅在浏览器处理，不会保存到服务器。",
    h1: "免费 WiFi 二维码（无需注册）",
    introduction: "一次扫描分享咖啡店或店铺访客 WiFi。网络名称与密码仅在您的浏览器中编码——我们不会上传或保存。",
    promise: "无需注册。密码仅在浏览器处理，不会保存到服务器。",
    body: [
      "WiFi 二维码编码网络名与密码，请仅向获准访客分享打印码。",
      "SSID、安全类型与密码完全在浏览器处理，本应用不上传、不存储、不记录。",
      "咖啡店常用 50 mm 宽贴纸或 A6 立牌（105×148 mm），QR 至少 25 mm。",
      "SSID 须与手机显示完全一致。覆膜前在路由器附近用 iPhone 与 Android 试扫——咖啡机旁蒸汽与反光可能遮挡边角。",
    ],
    examples: ["咖啡店柜台访客 WiFi", "小店铺访客网络", "家庭访客接入"],
    howTo: ["输入设备上显示的准确访客网络名", "选择 WPA 与密码（仅浏览器处理）", "选择 WiFi 模板，下载并在柜台试扫", "试扫成功后打印 50 mm 贴纸或 A6 立牌"],
    faqs: [
      { question: "你们会保存 WiFi 密码吗？", answer: "不会。仅在浏览器生成，不发送到服务器。" },
      { question: "柜台贴纸多大合适？", answer: "50 mm 宽贴纸或 A6 立牌，QR 至少 25 mm。" },
      { question: "需要账号吗？", answer: "不需要，可立即创建并下载。" },
      { question: "别人能从二维码读出密码吗？", answer: "可以，密码在二维码数据中，请只与可信访客分享。" },
    ],
    helperHint: "下载前请再次确认网络名称和安全类型。",
    frameText: "连接 WiFi",
    downloadFileName: "qr-wifi-free.png",
  },
  "hotel-wifi": {
    title: "酒店二维码（客人 WiFi）",
    description: "免费创建酒店客人 WiFi 二维码，用于房卡与大堂标识。密码仅在浏览器处理，使用独立访客网络。",
    h1: "酒店二维码：客人 WiFi",
    introduction: "将酒店二维码放在房卡、欢迎礼包或大堂标识上，让客人自行连接访客网络——切勿使用员工 WiFi。凭据仅在浏览器处理。",
    promise: "酒店风格设计，仅访客网络，立即可用，无需注册。",
    body: [
      "房卡常见尺寸为信用卡（85×55 mm）或 A6 插页（105×148 mm），QR 至少 25 mm。",
      "请使用独立访客 SSID——不是员工或后台网络。持有打印卡者可从二维码读取密码。",
      "WiFi 信息在浏览器本地编码，我们不会上传或存储酒店网络凭据。",
      "大批量印刷房卡前，请在真实客房内用 Android 与 iOS 试扫；访客密码轮换时请更换二维码。",
    ],
    examples: ["客房桌上 WiFi 卡", "大堂立牌", "欢迎手册插页"],
    howTo: ["输入访客网络名与密码（仅浏览器处理）", "选择酒店模板，设置简短边框如 Guest WiFi", "在真实客房内下载并试扫", "试扫成功后再打印房卡或大堂标识"],
    faqs: [
      { question: "客人应使用员工网络吗？", answer: "不应。请使用独立访客网络，改密后更新二维码。" },
      { question: "房卡上多大合适？", answer: "85×55 mm 或 A6 卡，QR 至少 25 mm 并留白。" },
      { question: "密码会保存在服务器吗？", answer: "不会，仅在浏览器创建静态 WiFi 码。" },
      { question: "每间房可印同一二维码吗？", answer: "可以，若所有房间共用同一访客网络。" },
    ],
    helperHint: "使用专用访客网络，并在客房内试扫。",
    frameText: "Guest WiFi",
    downloadFileName: "qr-hotel-wifi.png",
  },
  "google-review-shop": {
    title: "店铺 Google 评价二维码",
    description: "在手机上创建带边框的 Google 评价二维码。Google 自带码无自定义标签——在此设计柜台贴纸用码。",
    h1: "店铺 Google 评价二维码",
    introduction:
      "Google 商家资料提供评价链接，顾客可用手机在店内扫描——但 Google 下载的码无品牌边框。在此粘贴同一链接，添加「给我们评分」标签，用手机浏览器下载可打印 PNG。",
    promise: "支持手机设计，带边框评价链接，无需注册。",
    body: [
      "Google Business Profile 的评价链接用手机相机扫描即可打开公开评分页——适合收银台与收据。",
      "Google 内置下载是纯二维码，无店铺色与行动文案。此处可添加边框、颜色与「给我们评分」后再打印。",
      "柜台贴纸约 50×50 mm 或 A6 小立牌，QR 至少 25 mm 并留白。",
      "放在顾客结账处。大批量印刷前在手臂距离试扫——亮膜可能反光遮挡边角。",
    ],
    examples: ["50×50 mm 收银台贴纸", "收据感谢卡", "付款后袋贴"],
    howTo: ["从 Google Business Profile 复制评价链接", "粘贴于此，选择「给我们评分」模板并设置边框", "下载 PNG 并打印一张样张", "订购大量贴纸前先试扫"],
    faqs: [
      { question: "与 Google 自带评价码有何不同？", answer: "同一评价链接，但可添加颜色、边框与短文案，并可在手机上创建下载；Google 默认为无标签纯码。" },
      { question: "评价链接从哪里获取？", answer: "Google 商家资料 → 索取评价 → 复制分享链接。" },
      { question: "柜台贴纸多大合适？", answer: "50×50 mm 或 A6 立牌，QR 至少 25 mm，覆膜前先测试。" },
      { question: "可以强制顾客评价吗？", answer: "不可以。应在良好服务后邀请，并遵守 Google 政策。" },
    ],
    helperHint: "请使用 Google Business Profile 的官方评价链接。",
    frameText: "给我们评分",
    downloadFileName: "qr-google-review.png",
  },
  "business-contact-card": {
    title: "商务联系 / 数字名片二维码",
    description: "免费创建数字名片二维码，打开联系页、网站或公司简介。",
    h1: "商务联系 / 数字名片二维码",
    introduction: "不必再抄写长网址或电话。让合作伙伴一次扫描即可打开您的联系页或公司简介。",
    promise: "适合活动与客户拜访，无需注册。",
    body: [
      "数字名片二维码比每次改号都重印纸质名片更容易更新。",
      "可链接到关于页、联系页或汇总全部渠道的社交主页。",
    ],
    examples: ["印刷名片", "邮件签名与演示文稿", "展会展位"],
    howTo: ["准备联系页或简介网址", "选择商务模板并匹配品牌色", "试扫后放入名片或营销物料"],
    faqs: [
      { question: "一个二维码能覆盖多个渠道吗？", answer: "可以。链接到列出电话、邮箱和社交账号的页面即可。" },
      { question: "必须有自己的域名吗？", answer: "不必。任何可用的简介或落地页链接都可以。" },
    ],
    helperHint: "链接到信息完整的联系页，比把长文本塞进二维码更好。",
    frameText: "联系我们",
    downloadFileName: "qr-business-contact.png",
  },
  "storefront-promo": {
    title: "门店促销二维码",
    description: "免费创建门店促销二维码，链接优惠券、折扣或活动页，把路过客流转到手机。",
    h1: "门店促销二维码",
    introduction: "把二维码贴在橱窗、海报或货架上，让顾客立刻打开优惠或领券页面。",
    promise: "适合短周期活动，风格醒目，下载快速。",
    body: [
      "门店优惠在路径更短时转化更好。二维码可避免手输网址或优惠码。",
      "请在印刷物料上标注截止日期，活动结束后更新目标页。",
    ],
    examples: ["折扣券页面", "满赠登记页", "限定套餐链接"],
    howTo: ["先发布促销或优惠券页面", "粘贴链接并选择零售模板", "按门店观看距离试扫后再打印贴纸"],
    faqs: [
      { question: "多个活动能共用一个二维码吗？", answer: "仅当目标网址可改内容时可以；否则建议每个活动新建。" },
      { question: "应该贴在哪里？", answer: "顾客会停下来看的位置：橱窗、柜台和促销海报。" },
    ],
    helperHint: "链接到加载快、领取按钮清晰的促销页。",
    frameText: "领取优惠",
    downloadFileName: "qr-storefront-promo.png",
  },
  "event-poster": {
    title: "活动海报二维码",
    description: "免费创建活动海报二维码，链接报名页、行程或在线票务。",
    h1: "活动海报二维码",
    introduction: "在海报、传单和横幅上加入二维码，让感兴趣的人用手机立即报名或查看详情。",
    promise: "活动风格设计，大幅印刷仍清晰，无需注册。",
    body: [
      "海报空间有限。二维码可以把长详情放到手机页面，而不挤占主视觉。",
      "印刷后请在 1–2 米距离试扫，确认清晰度。",
    ],
    examples: ["报名或购票页", "地图与日程", "活动社群或主页链接"],
    howTo: ["准备报名或详情网址", "选择活动模板并设置短边框文字", "按海报观看距离试扫后再大批量印刷"],
    faqs: [
      { question: "海报表二维码要多大？", answer: "应大到在正常观看距离可轻松扫描，并保留周围留白。" },
      { question: "可用于线上活动吗？", answer: "可以。也可在幻灯片和邮件中链接到线上活动页。" },
    ],
    helperHint: "边框文字保持简短，例如“报名”或“查看详情”。",
    frameText: "立即报名",
    downloadFileName: "qr-event-poster.png",
  },
  "line-contact": {
    title: "LINE 官方账号二维码（门店与餐厅）",
    description: "用 LINE 加好友链接设计可打印二维码——柜台贴纸与立牌。不替代 LINE OA Manager。",
    h1: "LINE 官方账号二维码（门店与餐厅）",
    introduction:
      "从 LINE Official Account Manager 复制加好友链接，粘贴于此，下载带边框二维码用于柜台——OA 管理仍在 LINE 工具中，此页仅美化打印标牌。",
    promise: "粘贴 OA 加好友链接，为印刷调整边框。本站无需注册。",
    body: [
      "LINE Official Account Manager 仍负责 OA、广播与富菜单。此页仅将您复制的加好友 URL 转为带颜色与边框的可打印二维码。",
      "常见尺寸：50×50 mm 柜台贴纸、A6 立牌（105×148 mm）或收据页脚，QR 至少 25 mm。",
      "边框文字：添加 LINE、แอด LINE。请用已安装 LINE 的手机试扫。",
      "许多泰国餐厅在桌上放菜单码，柜台放 LINE 码用于点单与促销。",
    ],
    examples: ["来自 Official Account Manager 的 LINE OA 加好友链接", "含 LINE、电话和地图的联系汇总页", "点单、预约或排队聊天链接"],
    howTo: [
      "打开 LINE Official Account Manager 并复制加好友链接",
      "粘贴链接，设置短边框如「添加 LINE」，并预览设计",
      "下载用于 50 mm 贴纸或 A6 柜台立牌",
      "大批量印刷收据或包装前先试扫",
    ],
    faqs: [
      { question: "这会替代 LINE Official Account Manager 吗？", answer: "不会。OA、广播与菜单仍在 LINE 工具中管理；此处仅美化您复制的加好友链接二维码。" },
      { question: "贴纸或柜台立牌多大？", answer: "常见为 50×50 mm 贴纸与 A6 立牌（105×148 mm），QR 至少 25 mm。" },
      { question: "与 LINE 自带二维码有何不同？", answer: "可匹配品牌色、边框文字与模板，统一印刷风格。" },
      { question: "餐厅是否应与菜单码一起使用？", answer: "建议搭配：桌上菜单码，柜台 LINE 码。" },
      { question: "扫描者需要 LINE 应用吗？", answer: "需要，扫描手机须已安装 LINE。" },
    ],
    helperHint: "粘贴 LINE OA 加好友链接，或联系渠道汇总页网址。",
    frameText: "添加 LINE",
    downloadFileName: "qr-line-contact.png",
    toolLinks: [
      { label: "LINE 二维码生成器", barePath: "/qr-code/line" },
      { label: "泰式餐厅菜单二维码设计", barePath: "/use-cases/thai-restaurant-menu" },
      { label: "餐厅模板库", barePath: "/templates/restaurant" },
    ],
  },
  "restaurant-table-tent": {
    title: "餐厅桌牌菜单二维码设计",
    description: "桌牌尺寸 A6、QR 至少 30 mm。覆膜前先试扫。免费设计桌上菜单、WiFi 或评价桌牌码。",
    h1: "餐厅桌牌菜单二维码设计",
    introduction: "为 A6 折页立牌（105×148 mm）或亚克力架设计二维码，每张立牌一个清晰目标——覆膜前务必就座试扫。",
    promise: "提供毫米尺寸说明，每张立牌一个链接，无需注册。",
    body: [
      "标准折页桌牌常用 A6（105×148 mm）或 DL（99×210 mm）。QR 放在上部至少 30 mm，四周留白 5 mm。",
      "客人就座约 25–40 cm 处应能扫描。先打印真实尺寸样张放在桌上试扫，再大批量订购或覆膜。",
      "每张立牌一个目标最清晰：菜单、访客 WiFi 或 Google 评价。多目标请分开展牌或使用汇总页。",
      "亮膜与亚克力架可能反光——请在覆膜后测试，不要只在普通纸上试扫。",
    ],
    examples: ["A6 亚克力菜单立牌", "单链接折页卡", "独立的 WiFi 或评价立牌"],
    howTo: ["选定单一目标：菜单、WiFi 或评价", "用餐厅模板与短标签生成二维码", "打印 A6 真实尺寸样张并就座试扫", "试扫成功后再覆膜或大批量订购"],
    faqs: [
      { question: "桌牌上 QR 应多大了？", answer: "A6 立牌（105×148 mm）上 QR 至少 30 mm 并留白；DL 立牌比例相近。" },
      { question: "应先覆膜再测试吗？", answer: "不应。先印普通纸样张试扫，成功后再覆膜或订购亚克力架。" },
      { question: "一张立牌放几个链接？", answer: "一个目标最清晰；确需多项时使用汇总页。" },
      { question: "应从多远能扫到？", answer: "在就座高度 25–40 cm 处测试——典型餐椅伸手距离。" },
    ],
    helperHint: "为桌牌只选一个目标，例如菜单或 WiFi，避免客人困惑。",
    frameText: "桌边扫码",
    downloadFileName: "qr-table-tent.png",
  },
  "gmail-email": {
    title: "免费 Gmail / 邮件二维码",
    description: "免费创建 Gmail 或邮件二维码，无需注册。扫描后打开写邮件页面，并填好收件人、主题和正文。",
    h1: "免费 Gmail / 邮件二维码",
    introduction:
      "让客户或合作伙伴扫码后立刻打开邮件应用，收件人已填好。可添加主题和提示正文，适合名片、海报和店招。",
    promise: "只打开草稿，不会自动发送。支持 Gmail 和其他邮件应用。无需注册。",
    body: [
      "搜索 mail QR code 或 Gmail to QR code 的人，通常想要扫码后开始写邮件，而不是打开网页。",
      "本工具会生成带收件人、主题和正文的 mailto 二维码，因此手机上的 Gmail 和其他邮件应用都能打开草稿。",
    ],
    examples: ["打开销售邮箱的名片", "带 Resume 主题的招聘海报", "方便顾客提问的店内标识"],
    howTo: [
      "输入收件人邮箱",
      "按需要添加主题和提示正文",
      "用手机试扫，确认 Gmail 或默认邮件应用打开草稿，然后下载打印",
    ],
    faqs: [
      {
        question: "扫描后会立即发送邮件吗？",
        answer: "不会。只会打开草稿，用户仍需确认后再发送。",
      },
      {
        question: "支持 Gmail 吗？",
        answer: "支持。如果手机将 Gmail 设为默认邮件应用，扫描会打开 Gmail 写邮件界面。",
      },
      {
        question: "和网站二维码有何不同？",
        answer: "邮件二维码会打开邮件应用并填好收件人，而不会带用户去网页。",
      },
    ],
    helperHint: "输入收件人邮箱，并添加简短主题，例如咨询服务。",
    frameText: "发送邮件",
    downloadFileName: "qr-gmail-email.png",
  },
};

export const useCasesZh: Record<UseCaseSlug, UseCasePage> = Object.fromEntries(
  (Object.keys(copy) as UseCaseSlug[]).map((slug) => [slug, { ...useCaseMeta[slug], ...copy[slug] }]),
) as Record<UseCaseSlug, UseCasePage>;
