import { useCaseMeta } from "@/lib/seo/use-cases/catalog";
import type { UseCaseCopy, UseCasePage, UseCaseSlug } from "@/lib/seo/use-cases/types";

const copy: Record<UseCaseSlug, UseCaseCopy> = {
  "thai-restaurant-menu": {
    title: "泰式餐厅菜单二维码设计",
    description: "免费设计泰式餐厅菜单二维码，无需注册。链接电子菜单、自定义外观并下载可打印文件。",
    h1: "泰式餐厅菜单二维码设计",
    introduction: "设计可扫描的菜单二维码，让客人用手机查看泰语菜单，减少纸质菜单翻阅。适合经常更新菜品和价格的泰式餐厅。",
    promise: "浏览器内免费生成，无需账号，支持泰语链接和边框文字。",
    body: [
      "菜单二维码设计可降低重印成本，并通过更新链接页面快速调整价格。",
      "本页针对餐厅菜单与菜单二维码设计搜索意图，而不是只竞争宽泛的二维码生成词。",
    ],
    examples: ["Google 表格或网站菜单页", "在线托管的菜单 PDF", "午餐套餐与季节特选页"],
    howTo: ["准备适合手机打开的电子菜单链接", "粘贴网址并选择菜单模板", "设置简短边框文字，打印前先试扫"],
    faqs: [
      { question: "必须有自己的网站吗？", answer: "不必。可以链接到 Google Docs、网盘或其他电子菜单平台。" },
      { question: "支持泰文吗？", answer: "支持。链接和边框文字都可以使用泰文。" },
      { question: "需要注册吗？", answer: "不需要。可立即创建并下载，内容不会保存到我们的服务器。" },
    ],
    helperHint: "粘贴泰语电子菜单链接，并保持边框文字简短。",
    frameText: "查看菜单",
    downloadFileName: "qr-menu-thai-restaurant.png",
  },
  "cafe-menu": {
    title: "免费咖啡店菜单二维码设计",
    description: "免费设计咖啡店菜单二维码，无需注册。适合饮品、甜点和柜台促销的可扫描菜单码。",
    h1: "免费咖啡店菜单二维码设计",
    introduction: "设计咖啡店菜单二维码，让顾客在桌边或柜台快速打开饮品与甜点菜单，套用咖啡店风格后下载可打印图片。",
    promise: "免费、无需注册，提供咖啡店模板和实时预览。",
    body: [
      "咖啡店常更换季节饮品，菜单二维码设计可帮助切换链接，而不必每次重印整本菜单。",
      "如有需要，可为早间优惠或会员菜单使用不同活动链接。",
    ],
    examples: ["饮品与甜点网页菜单", "早间促销页", "预订或订位链接"],
    howTo: ["准备可在手机顺畅打开的咖啡店菜单链接", "选择咖啡店模板并粘贴网址", "试扫后放到桌面或柜台"],
    faqs: [
      { question: "可用于季节菜单吗？", answer: "可以。更新目标页面，或在网址变更时重新生成二维码。" },
      { question: "顾客需要安装 App 吗？", answer: "不需要。手机相机和浏览器即可。" },
    ],
    helperHint: "使用加载较快的咖啡店菜单链接，方便顾客快速点单。",
    frameText: "咖啡店菜单",
    downloadFileName: "qr-cafe-menu.png",
  },
  "free-wifi-no-signup": {
    title: "免费 WiFi 二维码（无需注册）",
    description: "免费创建 WiFi 二维码，无需注册。客人无需输入密码即可加入网络，支持 WPA 与开放网络。",
    h1: "免费 WiFi 二维码（无需注册）",
    introduction: "一次扫描即可分享 WiFi，不必反复告知密码。适合咖啡店、办公室和希望更快联网的店铺。",
    promise: "无需注册。密码仅在浏览器处理，不会保存到我们的服务器。",
    body: [
      "WiFi 二维码会编码网络名称和密码，请只分享给获准使用网络的人。",
      "本页对应“免费且无需注册的 WiFi 二维码”搜索意图。",
    ],
    examples: ["咖啡店访客 WiFi", "办公室访客网络", "家庭访客接入"],
    howTo: ["输入设备上显示的准确网络名称", "选择安全类型并在需要时填写密码", "在路由器附近试扫后下载到柜台使用"],
    faqs: [
      { question: "你们会保存 WiFi 密码吗？", answer: "不会。生成只在您的浏览器中完成。" },
      { question: "需要账号吗？", answer: "不需要。可立即创建并下载。" },
      { question: "别人能从二维码读出密码吗？", answer: "密码包含在二维码数据中，请只与可信访客分享。" },
    ],
    helperHint: "下载前请再次确认网络名称和安全类型。",
    frameText: "连接 WiFi",
    downloadFileName: "qr-wifi-free.png",
  },
  "hotel-wifi": {
    title: "酒店二维码（客人 WiFi）",
    description: "免费创建酒店二维码，用于客房或大堂 WiFi，客人无需询问前台即可联网。无需注册。",
    h1: "酒店二维码：客人 WiFi",
    introduction: "把酒店二维码放在客房卡片、欢迎礼包或大堂标识上，让客人自行连接 WiFi，减少前台咨询。",
    promise: "酒店风格设计，立即可用，无需注册。",
    body: [
      "搜索 hotel QR code 的用户通常需要客人 WiFi、房卡和大堂立牌，而不是通用生成器页。",
      "请使用访客网络，并在大批量打印前用 Android 和 iOS 试扫。",
    ],
    examples: ["客房 WiFi 卡", "大堂标识", "欢迎手册插页"],
    howTo: ["使用访客网络名称和密码", "选择酒店模板并设置简短边框文字", "在真实客房中试扫后再打印"],
    faqs: [
      { question: "客人应使用员工网络吗？", answer: "不应。请使用独立访客网络，并在改密后更新二维码。" },
      { question: "可以打印到每间客房吗？", answer: "可以。下载 PNG 后放到房卡或贴纸上。" },
    ],
    helperHint: "使用专用访客网络，并在客房内试扫。",
    frameText: "Guest WiFi",
    downloadFileName: "qr-hotel-wifi.png",
  },
  "google-review-shop": {
    title: "店铺 Google 评价二维码",
    description: "免费创建店铺 Google 评价二维码，结账后引导顾客直达评分页面。",
    h1: "店铺 Google 评价二维码",
    introduction: "把二维码放在收银台附近或收据上，让满意顾客一次扫描即可打开 Google 评价页。",
    promise: "直达评价链接，可自定义设计，无需注册。",
    body: [
      "本地店铺受益于真实评价。二维码可减少顾客搜索店铺的步骤。",
      "使用 Google Business Profile 的评价短链，搬迁门店时可重新生成。",
    ],
    examples: ["收银台贴纸", "感谢卡", "收据与包装"],
    howTo: ["从 Google Business Profile 复制评价链接", "粘贴到此处并选择评价模板", "试扫后放在顾客结账完成的位置"],
    faqs: [
      { question: "评价链接从哪里获取？", answer: "在 Google Business Profile 的分享/评分选项中获取。" },
      { question: "可以强制顾客评价吗？", answer: "不可以。应在服务后邀请反馈，并遵守 Google 政策。" },
    ],
    helperHint: "请使用 Google Business Profile 的官方评价链接。",
    frameText: "给我们评分",
    downloadFileName: "qr-google-review.png",
  },
  "business-contact-card": {
    title: "商务联系 / 数字名片二维码",
    description: "免费创建数字名片二维码，打开联系页、网站或公司简介。",
    h1: "商务联系 / 数字名片二维码",
    introduction: "不必再抄写长网址或电话。让合作伙伴一次扫描即可打开您的联系页或公司简介。",
    promise: "适合活动与客户拜访，无需注册。",
    body: [
      "数字名片二维码比每次改号都重印纸质名片更容易更新。",
      "可链接到关于页、联系页或汇总全部渠道的社交主页。",
    ],
    examples: ["印刷名片", "邮件签名与演示文稿", "展会展位"],
    howTo: ["准备联系页或简介网址", "选择商务模板并匹配品牌色", "试扫后放入名片或营销物料"],
    faqs: [
      { question: "一个二维码能覆盖多个渠道吗？", answer: "可以。链接到列出电话、邮箱和社交账号的页面即可。" },
      { question: "必须有自己的域名吗？", answer: "不必。任何可用的简介或落地页链接都可以。" },
    ],
    helperHint: "链接到信息完整的联系页，比把长文本塞进二维码更好。",
    frameText: "联系我们",
    downloadFileName: "qr-business-contact.png",
  },
  "storefront-promo": {
    title: "门店促销二维码",
    description: "免费创建门店促销二维码，链接优惠券、折扣或活动页，把路过客流转到手机。",
    h1: "门店促销二维码",
    introduction: "把二维码贴在橱窗、海报或货架上，让顾客立刻打开优惠或领券页面。",
    promise: "适合短周期活动，风格醒目，下载快速。",
    body: [
      "门店优惠在路径更短时转化更好。二维码可避免手输网址或优惠码。",
      "请在印刷物料上标注截止日期，活动结束后更新目标页。",
    ],
    examples: ["折扣券页面", "满赠登记页", "限定套餐链接"],
    howTo: ["先发布促销或优惠券页面", "粘贴链接并选择零售模板", "按门店观看距离试扫后再打印贴纸"],
    faqs: [
      { question: "多个活动能共用一个二维码吗？", answer: "仅当目标网址可改内容时可以；否则建议每个活动新建。" },
      { question: "应该贴在哪里？", answer: "顾客会停下来看的位置：橱窗、柜台和促销海报。" },
    ],
    helperHint: "链接到加载快、领取按钮清晰的促销页。",
    frameText: "领取优惠",
    downloadFileName: "qr-storefront-promo.png",
  },
  "event-poster": {
    title: "活动海报二维码",
    description: "免费创建活动海报二维码，链接报名页、行程或在线票务。",
    h1: "活动海报二维码",
    introduction: "在海报、传单和横幅上加入二维码，让感兴趣的人用手机立即报名或查看详情。",
    promise: "活动风格设计，大幅印刷仍清晰，无需注册。",
    body: [
      "海报空间有限。二维码可以把长详情放到手机页面，而不挤占主视觉。",
      "印刷后请在 1–2 米距离试扫，确认清晰度。",
    ],
    examples: ["报名或购票页", "地图与日程", "活动社群或主页链接"],
    howTo: ["准备报名或详情网址", "选择活动模板并设置短边框文字", "按海报观看距离试扫后再大批量印刷"],
    faqs: [
      { question: "海报表二维码要多大？", answer: "应大到在正常观看距离可轻松扫描，并保留周围留白。" },
      { question: "可用于线上活动吗？", answer: "可以。也可在幻灯片和邮件中链接到线上活动页。" },
    ],
    helperHint: "边框文字保持简短，例如“报名”或“查看详情”。",
    frameText: "立即报名",
    downloadFileName: "qr-event-poster.png",
  },
  "line-contact": {
    title: "LINE 或联系渠道二维码",
    description: "创建 LINE OA 或其他联系渠道二维码，方便顾客从门店快速加好友并联系。",
    h1: "LINE 或联系渠道二维码",
    introduction: "让顾客扫描即可添加 LINE 官方账号，或打开您指定的联系渠道，无需自行搜索店名。",
    promise: "适合以 LINE 为主渠道的店铺。本站无需注册。",
    body: [
      "许多泰国店铺通过 LINE 接单。直达加好友二维码可减少搜索步骤。",
      "如需多个渠道，也可链接到包含 LINE、电话和地图的汇总页。",
    ],
    examples: ["LINE OA 加好友链接", "联系渠道汇总页", "点单或排队聊天链接"],
    howTo: ["复制 LINE 加好友或联系网址", "粘贴到此处并设置短边框文字", "放到柜台或收据上后试扫"],
    faqs: [
      { question: "可以直接使用 LINE OA 链接吗？", answer: "可以。粘贴 LINE Official Account 的加好友网址即可。" },
      { question: "与 LINE 自带二维码有何不同？", answer: "您可以自定义边框和模板，使其更贴合店铺与印刷物料。" },
    ],
    helperHint: "粘贴 LINE OA 加好友链接，或联系渠道汇总页网址。",
    frameText: "添加 LINE",
    downloadFileName: "qr-line-contact.png",
  },
  "restaurant-table-tent": {
    title: "餐厅桌牌菜单二维码设计",
    description: "免费设计餐厅桌牌菜单二维码，从桌边打开菜单、WiFi 或评价页。无需注册。",
    h1: "餐厅桌牌菜单二维码设计",
    introduction: "为亚克力立牌或折页卡片设计桌牌菜单二维码，让客人无需呼叫服务员即可打开菜单、连接 WiFi 或留下评价。",
    promise: "适合小型桌牌，边框文字清晰，无需注册。",
    body: [
      "桌牌菜单二维码设计最好每张卡片只对应一个目标，避免一次扫描塞入多个动作。",
      "餐厅可分开菜单牌和评价牌，或在需要多选项时使用汇总页。",
    ],
    examples: ["亚克力菜单立牌", "含菜单与 WiFi 的折页卡", "含评价链接的感谢卡"],
    howTo: ["决定桌牌要打开菜单、WiFi 还是评价页", "用餐厅模板和短文案生成二维码", "先在桌上打印真实尺寸样张再大批量制作"],
    faqs: [
      { question: "一张桌牌放几个链接合适？", answer: "一个目标最清晰。若需要多项，请使用汇总页。" },
      { question: "桌牌上尺寸怎么选？", answer: "应大到坐着就能轻松扫描，并在下方放短文字。" },
    ],
    helperHint: "为桌牌只选一个目标，例如菜单或 WiFi，避免客人困惑。",
    frameText: "桌边扫码",
    downloadFileName: "qr-table-tent.png",
  },
  "gmail-email": {
    title: "免费 Gmail / 邮件二维码",
    description: "免费创建 Gmail 或邮件二维码，无需注册。扫描后打开写邮件页面，并填好收件人、主题和正文。",
    h1: "免费 Gmail / 邮件二维码",
    introduction:
      "让客户或合作伙伴扫码后立刻打开邮件应用，收件人已填好。可添加主题和提示正文，适合名片、海报和店招。",
    promise: "只打开草稿，不会自动发送。支持 Gmail 和其他邮件应用。无需注册。",
    body: [
      "搜索 mail QR code 或 Gmail to QR code 的人，通常想要扫码后开始写邮件，而不是打开网页。",
      "本工具会生成带收件人、主题和正文的 mailto 二维码，因此手机上的 Gmail 和其他邮件应用都能打开草稿。",
    ],
    examples: ["打开销售邮箱的名片", "带 Resume 主题的招聘海报", "方便顾客提问的店内标识"],
    howTo: [
      "输入收件人邮箱",
      "按需要添加主题和提示正文",
      "用手机试扫，确认 Gmail 或默认邮件应用打开草稿，然后下载打印",
    ],
    faqs: [
      {
        question: "扫描后会立即发送邮件吗？",
        answer: "不会。只会打开草稿，用户仍需确认后再发送。",
      },
      {
        question: "支持 Gmail 吗？",
        answer: "支持。如果手机将 Gmail 设为默认邮件应用，扫描会打开 Gmail 写邮件界面。",
      },
      {
        question: "和网站二维码有何不同？",
        answer: "邮件二维码会打开邮件应用并填好收件人，而不会带用户去网页。",
      },
    ],
    helperHint: "输入收件人邮箱，并添加简短主题，例如咨询服务。",
    frameText: "发送邮件",
    downloadFileName: "qr-gmail-email.png",
  },
};

export const useCasesZh: Record<UseCaseSlug, UseCasePage> = Object.fromEntries(
  (Object.keys(copy) as UseCaseSlug[]).map((slug) => [slug, { ...useCaseMeta[slug], ...copy[slug] }]),
) as Record<UseCaseSlug, UseCasePage>;
