# Interactive Clerk + Dynamic QR local env setup.
# Does NOT commit secrets. Writes frontend/.env.local and prints Railway env block.
param(
    [string]$PublishableKey,
    [string]$SecretKey,
    [string]$ClerkAuthority,
    [switch]$UseDevAuth
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envLocal = Join-Path $root "frontend\.env.local"

function Read-Secret([string]$Prompt) {
    $secure = Read-Host $Prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr) }
    finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr) }
}

Write-Host "== Clerk local setup =="
Write-Host "Create a Clerk app first: https://dashboard.clerk.com"
Write-Host ""

if (-not $PublishableKey) {
    $PublishableKey = Read-Host "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY (pk_test_... or pk_live_...)"
}
if (-not $SecretKey) {
    $SecretKey = Read-Secret "CLERK_SECRET_KEY (sk_test_... or sk_live_...)"
}
if (-not $ClerkAuthority) {
    Write-Host "Clerk Authority = Frontend API URL, e.g. https://your-app.clerk.accounts.dev"
    Write-Host "(Clerk Dashboard -> Configure -> Developers -> JWKS URL domain, or Frontend API)"
    $ClerkAuthority = Read-Host "Auth__ClerkAuthority"
}

$ClerkAuthority = $ClerkAuthority.Trim().TrimEnd("/")
$devAuth = if ($UseDevAuth) { "true" } else { "false" }

$vercelOidc = ""
if (Test-Path $envLocal) {
    $existing = Get-Content $envLocal -Raw
    if ($existing -match 'VERCEL_OIDC_TOKEN="[^"]*"') {
        $vercelOidc = $Matches[0]
    }
}

$lines = @(
    "# Generated by scripts/setup-clerk-env.ps1 — do not commit",
    $vercelOidc,
    "",
    "NEXT_PUBLIC_ENABLE_DYNAMIC_QR=true",
    "NEXT_PUBLIC_DYNAMIC_QR_DEV_AUTH=$devAuth",
    "NEXT_PUBLIC_API_BASE_URL=http://localhost:8080",
    "DYNAMIC_QR_API_ORIGIN=http://localhost:8080",
    "",
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PublishableKey",
    "CLERK_SECRET_KEY=$SecretKey"
) | Where-Object { $_ -ne "" }

Set-Content -Path $envLocal -Value ($lines -join "`n") -Encoding UTF8
Write-Host ""
Write-Host "Wrote $envLocal"
Write-Host ""
Write-Host "== Railway / API env (paste in Railway Variables) =="
Write-Host "Auth__ClerkAuthority=$ClerkAuthority"
Write-Host "Auth__AllowDevUserHeader=false"
Write-Host "DynamicQr__Enabled=true"
Write-Host "DynamicQr__PublicBaseUrl=http://localhost:8080"
Write-Host "DynamicQr__AllowLegacyOwnerToken=false"
Write-Host "Database__MigrateOnStartup=true"
Write-Host "Cors__AllowedOrigins__0=http://localhost:3000"
Write-Host ""
Write-Host "== Local API (PowerShell, separate terminal) =="
Write-Host '$env:Auth__ClerkAuthority="' + $ClerkAuthority + '"'
Write-Host '$env:Auth__AllowDevUserHeader="false"'
Write-Host '$env:DynamicQr__Enabled="true"'
Write-Host '$env:DynamicQr__PublicBaseUrl="http://localhost:8080"'
Write-Host '$env:DynamicQr__AllowLegacyOwnerToken="false"'
Write-Host '$env:ConnectionStrings__DefaultConnection="Host=localhost;Port=5432;Database=qrmarketing;Username=qrmarketing;Password=change-me-in-development"'
Write-Host '$env:Database__MigrateOnStartup="true"'
Write-Host '$env:DOTNET_ROLL_FORWARD="LatestMajor"'
Write-Host 'dotnet run --project .\backend\QrMarketing.Api\QrMarketing.Api.csproj --urls http://localhost:8080 --no-launch-profile --no-build'
Write-Host ""
Write-Host "== Next =="
Write-Host "1. Restart API with Auth__ClerkAuthority above"
Write-Host "2. cd frontend && npm run dev"
Write-Host "3. Open http://localhost:3000/en/sign-up"
Write-Host "4. After sign-in, test Dynamic tab + /en/my/dynamic-qr"
