// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMarketing.Api.Data;

#nullable disable

namespace QrMarketing.Api.Data.Migrations
{
    [DbContext(typeof(QrMarketingDbContext))]
    [Migration("20260828100000_AddUsersAndEntitlements")]
    partial class AddUsersAndEntitlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in QrMarketingDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
