// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMarketing.Api.Data;

#nullable disable

namespace QrMarketing.Api.Data.Migrations
{
    [DbContext(typeof(QrMarketingDbContext))]
    partial class QrMarketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QrMarketing.Api.Data.Entities.DynamicQr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerTokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerTokenHash")
                        .HasDatabaseName("idx_dynamic_qr_owner_token_hash");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("dynamic_qr", (string)null);
                });

            modelBuilder.Entity("QrMarketing.Api.Data.Entities.ScanEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("char(2)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("QrId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referrer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QrId", "ScannedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_scan_events_qr_id_time");

                    b.ToTable("scan_events", (string)null);
                });

            modelBuilder.Entity("QrMarketing.Api.Data.Entities.ScanEvent", b =>
                {
                    b.HasOne("QrMarketing.Api.Data.Entities.DynamicQr", "Qr")
                        .WithMany("ScanEvents")
                        .HasForeignKey("QrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Qr");
                });

            modelBuilder.Entity("QrMarketing.Api.Data.Entities.DynamicQr", b =>
                {
                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
